#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════
# CogLog CLI — Shell script edition
#
# Glue language implementation: bash + jq.
#
# CogLog's entire operation reduces to file I/O and JSON transformation.
# This script makes that reduction explicit: read is cat, clear is rm,
# write is jq piped through mv. The only non-POSIX dependency is jq —
# and the fact that jq alone suffices is itself a proof of CogLog's
# essential simplicity.
#
# Usage:
#   coglog-cli.sh read
#   coglog-cli.sh write < input.json
#   coglog-cli.sh clear
#
# Environment:
#   COGLOG_DIR  Override data directory (default: ~/.coglog)
# ═══════════════════════════════════════════════════════════════════

set -euo pipefail

readonly COGLOG_VERSION="0.9.1"  # @coglog-version
readonly COGLOG_DIR="${COGLOG_DIR:-${HOME}/.coglog}"
readonly COGLOG_FILE="${COGLOG_DIR}/current.json"

# ═══════════════════════════════════════════════════════════════════
# jq dependency check
# ═══════════════════════════════════════════════════════════════════

require_jq() {
  command -v jq >/dev/null 2>&1 && return 0

  echo "coglog-cli: error: jq is required but not found." >&2
  echo "" >&2

  case "$(uname -s)" in
    Linux*)
      if   command -v apk     >/dev/null 2>&1; then echo "  apk add jq"                >&2
      elif command -v apt-get >/dev/null 2>&1; then echo "  sudo apt-get install jq"    >&2
      elif command -v dnf     >/dev/null 2>&1; then echo "  sudo dnf install jq"        >&2
      elif command -v pacman  >/dev/null 2>&1; then echo "  sudo pacman -S jq"          >&2
      elif command -v zypper  >/dev/null 2>&1; then echo "  sudo zypper install jq"     >&2
      else                                          echo "  https://jqlang.github.io/jq/download/" >&2
      fi ;;
    Darwin*)
      echo "  brew install jq" >&2 ;;
    MINGW*|MSYS*|CYGWIN*)
      echo "  winget install jqlang.jq" >&2 ;;
    *)
      echo "  https://jqlang.github.io/jq/download/" >&2 ;;
  esac

  exit 1
}

# ═══════════════════════════════════════════════════════════════════
# _schema — jq filter that builds the self-documenting schema
#
# Every CogLog entry carries its own reading instructions.
# In the shell script edition, the schema is a jq expression:
# data generated by a data-transformation tool. The medium is
# consistent — jq speaks JSON natively.
# ═══════════════════════════════════════════════════════════════════

# @coglog-version (next line: version in jq filter)
readonly SCHEMA_FILTER='{
  version: "0.9.1",
  fact_layer: {
    user:      "non-empty string required — user'\''s original utterance",
    thinking:  "non-empty string required — AI'\''s full thinking process",
    assistant: "non-empty string required — AI'\''s original output"
  },
  interpretation_layer: {
    current_focus:  "string required, empty OK — present: what am I working on?",
    theory_of_mind: "string required, empty OK — other: what is the user'\''s state?",
    self_narrative:  "string required, empty OK — self: who am I in this moment?",
    annotation:     "string required, empty OK — future: what should I do next?"
  },
  constraints: {
    window_size:          "1 turn (overwritten each write)",
    interpretation_empty: "choosing not to write is itself a metacognitive act"
  }
}'

# ═══════════════════════════════════════════════════════════════════
# read — cat through jq for consistent pretty-printing
# ═══════════════════════════════════════════════════════════════════

cmd_read() {
  if [[ ! -f "$COGLOG_FILE" ]]; then
    echo "(no coglog found)"
    return 0
  fi
  jq '.' "$COGLOG_FILE"
}

# ═══════════════════════════════════════════════════════════════════
# write — validate, transform, atomically commit
#
# Pipeline:
#   stdin → jq(validate) → jq(build entry) → tmpfile → mv → done
#
# The atomic write (mktemp + mv) is the shell idiom for safe file
# replacement. If jq fails mid-transform, current.json is untouched.
# Other implementations (Python's open("w"), Rust's fs::write) lack
# this protection. The glue version is, in this regard, more robust.
# ═══════════════════════════════════════════════════════════════════

cmd_write() {
  local input
  input=$(cat)

  if [[ -z "$input" ]]; then
    echo "coglog error: no input on stdin" >&2
    return 1
  fi

  # Parse and extract fields — let jq handle all JSON concerns
  local parsed
  if ! parsed=$(echo "$input" | jq -e '{
    user:            .user,
    thinking:        .thinking,
    assistant:       .assistant,
    current_focus:   .current_focus,
    theory_of_mind:  .theory_of_mind,
    self_narrative:  .self_narrative,
    annotation:      .annotation
  }' 2>&1); then
    echo "coglog error: parse: ${parsed}" >&2
    return 1
  fi

  # Validate fact layer: non-empty strings
  local fact_error
  if fact_error=$(echo "$parsed" | jq -e -r '
    . as $data |
    ["user", "thinking", "assistant"][] |
    . as $key |
    if ($data[$key] | type) != "string" then
      "missing required field: " + $key
    elif ($data[$key] | length) == 0 then
      "missing required field: " + $key
    else
      empty
    end
  ' 2>&1); then
    echo "coglog error: validation: ${fact_error}" >&2
    return 1
  fi

  # Validate interpretation layer: strings required (empty OK)
  local interp_error
  if interp_error=$(echo "$parsed" | jq -e -r '
    . as $data |
    ["current_focus", "theory_of_mind", "self_narrative", "annotation"][] |
    . as $key |
    if ($data[$key] | type) != "string" then
      "missing required field: " + $key + " (empty string is acceptable)"
    else
      empty
    end
  ' 2>&1); then
    echo "coglog error: validation: ${interp_error}" >&2
    return 1
  fi

  # Read previous turn_id
  local turn_id=1
  if [[ -f "$COGLOG_FILE" ]]; then
    local prev_id
    prev_id=$(jq -r '.turn_id // 0' "$COGLOG_FILE" 2>/dev/null || echo 0)
    turn_id=$(( prev_id + 1 ))
  fi

  # Timestamp
  local timestamp
  timestamp=$(date -u +%Y-%m-%dT%H:%M:%SZ)

  # Build entry — single jq invocation assembles the complete JSON
  mkdir -p "$COGLOG_DIR"
  local tmp
  tmp=$(mktemp "${COGLOG_DIR}/current.XXXXXX")

  if ! echo "$parsed" | jq -n \
    --argjson schema "$(jq -n "$SCHEMA_FILTER")" \
    --argjson turn_id "$turn_id" \
    --arg     timestamp "$timestamp" \
    --argjson fields "$(cat)" \
    '{
      _schema:        $schema,
      turn_id:        $turn_id,
      timestamp:      $timestamp,
      layers: {
        user:         $fields.user,
        thinking:     $fields.thinking,
        assistant:    $fields.assistant
      },
      current_focus:  $fields.current_focus,
      theory_of_mind: $fields.theory_of_mind,
      self_narrative:  $fields.self_narrative,
      annotation:     $fields.annotation
    }' > "$tmp" 2>&1; then
    rm -f "$tmp"
    echo "coglog error: failed to build entry" >&2
    return 1
  fi

  # Atomic commit
  mv -f "$tmp" "$COGLOG_FILE"

  echo "coglog: turn ${turn_id} written"
}

# ═══════════════════════════════════════════════════════════════════
# clear — rm
# ═══════════════════════════════════════════════════════════════════

cmd_clear() {
  if [[ -f "$COGLOG_FILE" ]]; then
    rm -f "$COGLOG_FILE"
    echo "coglog: cleared"
  else
    echo "coglog: no existing coglog"
  fi
}

# ═══════════════════════════════════════════════════════════════════
# usage
# ═══════════════════════════════════════════════════════════════════

cmd_usage() {
  cat <<'EOF'
usage: coglog-cli.sh <read|write|clear>

  read    — display the previous turn's coglog
  write   — save current turn (reads JSON from stdin)
  clear   — reset coglog

write expects JSON on stdin (all fields required):
  {
    "user": "user's message",
    "thinking": "AI thinking process",
    "assistant": "AI output",
    "current_focus": "what is happening right now",
    "theory_of_mind": "user intent/state inference",
    "self_narrative": "improvised self-story at this moment",
    "annotation": "note to future self"
  }

  fact layer (user, thinking, assistant): non-empty string required
  interpretation layer (current_focus, theory_of_mind,
    self_narrative, annotation): string required, empty string acceptable

environment:
  COGLOG_DIR  data directory (default: ~/.coglog)

requires: jq (https://jqlang.github.io/jq/)
EOF
}

# ═══════════════════════════════════════════════════════════════════
# main — dispatch
# ═══════════════════════════════════════════════════════════════════

main() {
  require_jq

  case "${1:-}" in
    read)  cmd_read  ;;
    write) cmd_write ;;
    clear) cmd_clear ;;
    *)     cmd_usage
           [[ -n "${1:-}" ]] && exit 1 || exit 0
           ;;
  esac
}

main "$@"
