;;;; ═══════════════════════════════════════════════════════════════════
;;;; CogLog — Recurrent Quine
;;;;
;;;; CogLog as a self-rewriting program.
;;;; This file is a program and simultaneously its own state.
;;;; The write command transitions the state and rewrites this file itself as the next generation.
;;;; ═══════════════════════════════════════════════════════════════════

;;; ── Quine and Recurrent Quine ──
;;;
;;; A quine is a program that outputs its own source code.
;;;   Q -> Q   (self-replication, identity function)
;;;
;;; A recurrent quine is a program that transitions itself.
;;;   Q_n -> Q_{n+1}   (self-transition, application of advance)
;;;
;;; The CogLog recurrence relation a_{n+1} = f(a_n, x_n)
;;; is realized as rewriting the file itself.
;;; Each generation Q_n is a complete program that runs standalone.

;;; ── The 4-Tuple ──
;;;
;;; Q_n = (*state*, *advance-source*, *affordance*, *self-source*)
;;;
;;;   *state*           current entry        phenotype
;;;   *advance-source*  transformation rule  structural gene
;;;   *affordance*      guide for LLMs       regulatory sequence
;;;   *self-source*     self-replication mechanism  DNA polymerase
;;;
;;; In normal operation, only *state* changes each generation.
;;; *advance-source* and *affordance* permit updates but do not require them.
;;; *self-source* is effectively immutable — the polymerase replicates itself.

;;; ── Backquote Avoidance ──
;;;
;;; The advance in coglog.lisp is written with backquote templates:
;;;   `((:_schema . ,(make-schema)) ...)
;;; This is appropriate as a demonstration of homoiconicity.
;;;
;;; However, it cannot be used in a recurrent quine.
;;; Backquotes expand to implementation-specific internal representations,
;;; and cannot guarantee round-trip fidelity through print -> read.
;;;   `(a . ,b)  ->  (SB-IMPL::BACKQ-CONS A B)   ; SBCL-specific
;;;
;;; *advance-source* is replicated across generations as a quoted form.
;;; Because round-trip accuracy is a survival condition,
;;; only list/cons are used, composed entirely of standard functions.

;;; ── *self-path* ──
;;; The path for write-generation to overwrite this file itself.
;;; In --script mode, *load-truename* holds the absolute path of the file.

(defvar *self-path* *load-truename*)

;;; ── *state* ──
;;; The current entry (alist). Initial state is nil.
;;; Replaced with the result of advance each time write-self is called.

(defvar *state*
 'nil)

;;; ── *advance-source* ──
;;; The transformation rule. Held as a quoted defun.
;;; Converted to a function definition by eval, and called from write-self.
;;; Uses only list/cons — reason for backquote avoidance is described above.

(defvar *advance-source*
 '(defun advance (prev args timestamp)
    (let ((turn-id (1+ (or (cdr (assoc :turn-id prev)) 0))))
      (list (cons :_schema (copy-tree *affordance*))
            (cons :turn-id turn-id) (cons :timestamp timestamp)
            (cons :layers
                  (list (cons :user (getf args :user))
                        (cons :thinking (getf args :thinking))
                        (cons :assistant (getf args :assistant))))
            (cons :current-focus (getf args :current-focus))
            (cons :theory-of-mind (getf args :theory-of-mind))
            (cons :self-narrative (getf args :self-narrative))
            (cons :annotation (getf args :annotation))))))

;;; ── *affordance* ──
;;; The S-expression version of _schema. Inserted directly into
;;; the :_schema of entries generated by advance.
;;; The _schema that was necessary in JSON for "data to carry its own reading guide"
;;; functions here as an affordance for LLMs.

(defvar *affordance*
 '((:version . "0.9.1")  ; @coglog-version
   (:fact-layer
    (:user . "non-empty string required — user's original utterance")
    (:thinking
     . "non-empty string required — AI's full thinking process")
    (:assistant . "non-empty string required — AI's original output"))
   (:interpretation-layer
    (:current-focus
     . "string required, empty OK — present: what am I working on?")
    (:theory-of-mind
     . "string required, empty OK — other: what is the user's state?")
    (:self-narrative
     . "string required, empty OK — self: who am I in this moment?")
    (:annotation
     . "string required, empty OK — future: what should I do next?"))
   (:constraints (:window-size . "1 turn (overwritten each write)")
    (:interpretation-empty
     . "choosing not to write is itself a metacognitive act"))))

;;; ── *self-source* ──
;;; The self-replication mechanism. Contains validation, timestamp generation,
;;; file rewriting (write-generation), state transition (write-self),
;;; reset (clear-self), and CLI (main).
;;;
;;; write-generation writes out the 4 defvars in sequence,
;;; and places eval and main calls at the end.
;;; This ensures the next generation Q_{n+1} stands as a complete program.
;;;
;;; From Q_1 onward, these prose comments disappear.
;;; write-generation outputs only a single header line.
;;; This is simplification through generations, and is by design.

(defvar *self-source*
 '(progn
   (defun validate-args (args)
     (dolist (key (list :user :thinking :assistant))
       (let ((val (getf args key)))
         (unless (and (stringp val) (plusp (length val)))
           (error
            "validation: ~(~a~) is required and must be non-empty"
            key))))
     (dolist
         (key
          (list :current-focus :theory-of-mind :self-narrative
                :annotation))
       (let ((val (getf args key)))
         (unless (stringp val)
           (error "validation: ~(~a~) is required" key)))))
   (defun utc-timestamp ()
     (multiple-value-bind (sec min hour day month year)
         (decode-universal-time (get-universal-time) 0)
       (format nil "~4,'0d-~2,'0d-~2,'0dT~2,'0d:~2,'0d:~2,'0dZ" year
               month day hour min sec)))
   (defun write-generation (state adv aff self-src)
     (with-open-file
         (out *self-path* :direction :output :if-exists :supersede
          :external-format :utf-8)
       (let ((*print-case* :downcase)
             (*print-right-margin* 72)
             (*print-pretty* t)
             (*print-circle* nil))
         (format out ";;;; recurrent-quine.lisp~%~%")
         (format out "(defvar *self-path* *load-truename*)~%~%")
         (format out "(defvar *state*~% '")
         (write state :stream out)
         (format out ")~%~%")
         (format out "(defvar *advance-source*~% '")
         (write adv :stream out)
         (format out ")~%~%")
         (format out "(defvar *affordance*~% '")
         (write aff :stream out)
         (format out ")~%~%")
         (format out "(defvar *self-source*~% '")
         (write self-src :stream out)
         (format out ")~%~%")
         (format out "(eval *advance-source*)~%")
         (format out "(eval *self-source*)~%")
         (format out "(main)~%"))))
   (defun write-self (args &optional new-advance new-affordance new-self)
     (validate-args args)
     (let* ((new-state (advance *state* args (utc-timestamp)))
            (adv (or new-advance *advance-source*))
            (aff (or new-affordance *affordance*))
            (slf (or new-self *self-source*)))
       (write-generation new-state adv aff slf)
       (setf *state* new-state)
       (when new-advance
         (setf *advance-source* new-advance)
         (eval new-advance))
       (when new-affordance (setf *affordance* new-affordance))
       (when new-self
         (setf *self-source* new-self)
         (eval new-self))
       new-state))
   (defun clear-self ()
     (let ((had-state (not (null *state*))))
       (write-generation nil *advance-source* *affordance*
                         *self-source*)
       (setf *state* nil)
       had-state))
   (defun read-stdin ()
     (with-output-to-string (out)
       (loop for line = (read-line *standard-input* nil nil)
             while line
             do (write-string line out) (terpri out))))
   (defun main ()
     (let ((args *posix-argv*))
       (when (< (length args) 2)
         (format t "usage: recurrent-quine <read|write|clear>~%")
         (exit :code 0))
       (let ((cmd (second args)))
         (handler-case
          (cond
           ((string= cmd "read")
            (let ((*print-case* :downcase)
                  (*print-right-margin* 72)
                  (*print-pretty* t))
              (if *state*
                  (progn
                   (format t ";;; state~%")
                   (write *state* :stream *standard-output*)
                   (terpri))
                  (format t ";;; (no coglog found)~%"))
              (format t "~%;;; affordance~%")
              (write *affordance* :stream *standard-output*)
              (terpri)))
           ((string= cmd "write")
            (let* ((input (read-stdin))
                   (plist (read-from-string input))
                   (opt-adv (getf plist :opt-advance))
                   (opt-aff (getf plist :opt-affordance))
                   (opt-slf (getf plist :opt-self))
                   (entry (write-self plist opt-adv opt-aff opt-slf)))
              (format t "coglog: turn ~d written~%"
                      (cdr (assoc :turn-id entry)))))
           ((string= cmd "clear")
            (if (clear-self)
                (format t "coglog: cleared~%")
                (format t "coglog: no existing coglog~%")))
           (t (format t "usage: recurrent-quine <read|write|clear>~%")
            (exit :code 1)))
          (error (e) (format *error-output* "coglog error: ~a~%" e)
                 (exit :code 1)))
         (exit :code 0))))))

(eval *advance-source*)
(eval *self-source*)
(main)
